[package]
name = "multicast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "chat"
path = "examples/chat/main.rs"
required-features = ["chat"]

[features]
debug = ["logger/debug"]
chat = ["cli", "uuid/serde"]
cli = ["dep:clap", "tokio/signal", "dep:crossterm", "dep:futures-core", "dep:futures"]
ci_tests = []

[dependencies]
clap = { version = "4.5.4", optional = true, features = ["derive"] }
crossterm = { version = "0.27.0", features = ["event-stream"], optional = true}
deadqueue = "0.2.4"
futures = { version = "0.3.30", optional = true }
futures-core = { version = "0.3.30", default-features = false, optional = true }
fxhash = { version = "0.2.1" }
logger = { version = "0.1.0", path = "../logger", default-features = false}
prost = "0.12.4"
prost-types = "0.12.4"
serde = "1.0.197"
serde_json = "1.0.115"
socket2 = "0.5.6"
tokio = { version = "1.37.0", features = ["net", "time", "rt-multi-thread", "macros", "sync"] }
tokio_socket2 = "0.1.1"
uuid = { version = "1.8.0", features = ["v4", "serde"] }

[build-dependencies]
prost-build = "0.12.4"

[dev-dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serial_test = "3.1.1"
