name: Rust

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

env:
  CARGO_TERM_COLOR: always
  PROTOC_VERSION: 3.23.4

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hecrj/setup-rust-action@v2
    - name: Install protoc
      uses: taiki-e/install-action@v2
      with:
        tool: protoc@${{ env.PROTOC_VERSION }}
    - name: Build
      run: cargo build --verbose --features=example
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Check clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
